# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "<your-dev-client-id>"
name = "shopiflare-dev"
application_url = "https://<your-tunnel-subdomain>.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://<your-tunnel-subdomain>.trycloudflare.com/auth/callback",
  "https://<your-tunnel-subdomain>.trycloudflare.com/auth/shopify/callback",
  "https://<your-tunnel-subdomain>.trycloudflare.com/api/auth/callback"
]
